%% Compile dependencies first...
{'deps/mochiweb/src/*',[{outdir, "ebin"}, {i, "deps/mochiweb/include"}]}.
%% Compile behaviours...
{'src/backend',[{outdir, "ebin"}]}.
%% Compile the remaining source code
{'src/*',[{outdir, "ebin"}]}.
